# Embedded Server configuration
server:
    port: 8001
#    compression:
#        enabled: true
#    tomcat:
#        uri-encoding: UTF-8
#    error:
#        include-stacktrace: never

# Spring configuration
spring:
    webflux:
        base-path: /specialties/v1

    application:
        name: specialties
        version: 1.0.0
        log: /logs
    messages:
        encoding: UTF-8
    version: 2.4.0
    main:
        banner-mode: log
        lazy-initialization: false
    mvc:
        converters:
            preferred-json-mapper: jsonb
    jpa:
        open-in-view: false
        show-sql: true
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                temp:
                    use_jdbc_metadata_defaults: false
    datasource:
        initialization-mode: never
        hikari:
            connection-init-sql: SELECT 1
            connection-test-query: SELECT 1
            allow-pool-suspension: false
            auto-commit: true
            connection-timeout: 3000
            idle-timeout: 600000
            leak-detection-threshold: 45000
            max-lifetime: 1800000
            minimum-idle: 10
            maximum-pool-size: 20
            validation-timeout: 5000
        driverClassName: org.postgresql.Driver
        password: postgres
        username: postgres
        url: jdbc:postgresql://localhost:5438/postgres



# Logger Configuration
logging:
    level:
        root: INFO